application:
  external_plugins_directory: plugins
  logs_level: INFO
  plugins_directory: src/plugins
  plugins_enabled: true
  theme: dark
devices:
  auto_discover: true
  refresh_interval: 60
general:
  update_channel: Stable
  repository_url: ""
  check_for_updates: true
  auto_update: false
update:
  auto_initialize_git: true
  git_remote_url: ""
  update_strategy: git
ui:
  device_table:
    default_columns:
    - name
    - ip
    - status
  font_size: 10
  show_statusbar: true
  toolbar_position: top
